// Typed API client generated from the backend's OpenAPI contract (05 §6.2
// guardrail 2). Types in schema.d.ts are generated by `npm run generate:api`
// from the vendored openapi.json (pinned backend commit in package.json).
// NEVER hand-edit schema.d.ts; regenerate it.
import createClient from 'openapi-fetch'

import type { paths } from './schema'

const baseUrl = import.meta.env.VITE_API_BASE_URL ?? 'http://localhost:8000'

export const api = createClient<paths>({ baseUrl })
export type { paths }
